# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sartaj Singh
tagline:             'TODO'
description:         'TODO'
url:                 https://leosartaj.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sartaj Singh
  url:               https://github.com/leosartaj
  email:             singhsartaj94@gmail.com

# Custom vars
version:             1.0.0

timezone: Asia/Varanasi
