# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sartaj Singh
tagline:             Some line
url:                 http://github.com/leosartaj
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sartaj Singh
  url:               https://github.com/leosartaj
  email:             singhsartaj94@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/leosartaj/leosartaj.github.io
