# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#
permalink:           pretty

# Setup
title:               Sartaj Singh
tagline:             ': Open Source Enthusiast'
description:         'Programming . Mathematics . Awesomeness'
url:                 https://sartajsingh.dev
baseurl:             ''
paginate:            1

# About
author:
  name:              Sartaj Singh
  url:               https://github.com/leosartaj
  email:             singhsartaj94@gmail.com

# Contact
contact:
  github:            http://github.com/leosartaj
  twitter:           http://twitter.com/leosartaj03
  quora:             http://quora.com/Sartaj-Singh-27
  mail:              mailto:singhsartaj94@gmail.com

feedback:          http://github.com/leosartaj/leosartaj.github.io/issues/new

excerpt_separator:   <!-- excerpt -->
timezone: Asia/Varanasi
